### ISSUE TITLE
Logs still come as "success"

### ISSUE THREAD

**Issue by drew-fc** [briandunnington/AzureFunctionsIsolatedHttpTelemetry#1]
hi @briandunnington ,
thanks for putting this together.
I am following your example, but AppInsights still records my function call as success, even though I return a 500 from my exception logging middleware.

Here's the simplified example:
![image](https://github.com/briandunnington/AzureFunctionsIsolatedHttpTelemetry/assets/40699052/053ed4f8-33db-4ffe-a71a-37919dcedba5)
```

using System;
using System.Net;
using Element.Azure.Functions.Worker.Extensions.HttpTelemetry;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace AzureFunctionApp.Functions
{
 
    public class Function
    {
        private readonly ILogger _logger;

        public Function(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function>();
        }

        [Function("Function")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req,
            [HttpTelemetry] object ignore)
        {
            var response = req.CreateResponse(HttpStatusCode.InternalServerError);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Welcome to Azure Functions!");

            return response;
        }
    }
}

```

**Comment by briandunnington** [comment]
Hi @drew-fc - this package only sets the Success status on `RequestTelemetry` (https://github.com/briandunnington/AzureFunctionsIsolatedHttpTelemetry/blob/5038fded6d1db0f2c822d3f2c400c0d35c3c9b29/Element.Azure.WebJobs.Extensions.HttpTelemetry/Startup.cs#L33C1-L34C32) - so it wont affect `TraceTelemetry` like in your screenshot.
